Release v0.0.4
- fix: TypeError: __init__() missing 1 required positional argument: 'app_name'
- fix: AttributeError: 'dict' object has no attribute 'setup'
- fix: AttributeError: module 'os' has no attribute 'setpgrgp'